### PR TITLE
uptaded readme and route.js

### PR DESCRIPTION
**Pull request by hknfrt**

### CODE REVIEW

**Comment by hknfrt** [comment]
Hi is there any problem to fix ?

**Comment by judygab** [comment]
> Hi is there any problem to fix ?

taking a look now @hknfrt

**Comment by judygab** [comment]
looks good, merging and closing the pr. Thank you for your contribution!

**Comment by hknfrt** [comment]
Anytime, and one of my plan too, I will try to build TS version of it, as soon as possible, see ya

**Pull request merged**
